### ISSUE TITLE
demo.sh error and Running the Kolide server error

### ISSUE THREAD

**Issue by dnayr81** [kolide/kolide-quickstart#25]
1. I had an error when running quickstart script on both CentOS and Ubuntu. 

```
[root@localhost kolide-quickstart]# ./demo.sh up simple [license string]
Using default tag: latest
latest: Pulling from kolide/kolide
Digest: sha256:9a802751690fe3a93f7c11d084128fa631cba964d22c772ff58b153d01034e91
Status: Image is up to date for kolide/kolide:latest
Using default tag: latest
latest: Pulling from kolide/openssl
Digest: sha256:9d86215afdd5d76faae9de32b7be862a64542ff7ddcc753c43b34118f42aead8
Status: Image is up to date for kolide/openssl:latest
kolidequickstart_redis_1 is up-to-date
Starting kolidequickstart_mysql_1
kolidequickstart_mailhog_1 is up-to-date
Starting kolidequickstart_kolide_1
Waiting for MySQL to accept connections...
.\C
Error: MySQL failed to start up. Exiting.
[root@localhost kolide-quickstart]# 
```

2. CentOS error when preparing db (CentOS/Ubuntu):

```
/usr/bin/kolide prepare db \
>     --mysql_address=127.0.0.1:3306 \
>     --mysql_database=kolide \
>     --mysql_username=root \
>     --mysql_password=toor
2017/02/21 15:04:36 FAIL 20161118212641_CreateTablePasswordResetRequests.go (Error 1067: Invalid default value for 'expires_at'), quitting migration.
```

**Comment by groob** [comment]
Thanks for reporting the issue. We've only tested the script on macOS so far. 
I'll try to duplicate the errors with docker on ubuntu/centos and resolve any differences.

**Comment by Centurion89** [comment]
Having the exact same error on Ubuntu 14.04 at the moment. Happy to provide any info that would be helpful in diagnosing the issue.

**Comment by groob** [comment]
Thanks for the feedback. I've been working on troubleshooting this issue today and will have a PR with a fix soon.

**Comment by Centurion89** [comment]
@groob is there a way to quickly reset our docker environment to test the fix or is that not necessary?

**Comment by groob** [comment]
@Centurion89 I tested it myself, but it would be great to get a confirmation

```
# remove existing containers (note this will remove any containers on the host. you can also remove # the kolide ones manually if you'd prefer
docker rm -f $(docker ps -a -q)

# clone my fork
git clone https://github.com/groob/kolide-quickstart.git

# check out the branch
cd kolide-quickstart &&  git checkout initialize && cd ..

# run through the usual steps in the quickstart 
cd kolide-quickstart && ./demo.sh up simple <license>

**Comment by zwass** [comment]
Does the `osquery_status` log file show up after adding some hosts?

**Comment by groob** [comment]
@zwass yes it does.

**Comment by groob** [comment]
The only container that had any issues was mysql, because it adds a custom user and group
https://github.com/docker-library/mysql/blob/eeb0c33dfcad3db46a0dfb24c352d2a1601c7667/5.7/Dockerfile#L4

**Comment by Centurion89** [comment]
@groob fix confirmed - thanks!

**Comment by groob** [comment]
Merging, thanks for the verification 👍

**Comment by dnayr81** [comment]
Wow! Tested and is now up and running! 

Great work guys!
