### ISSUE TITLE
Ubuntu: FAIL 20161118212641_CreateTablePasswordResetRequests.go

### ISSUE THREAD

**Issue by stachdude** [kolide/kolide-quickstart#31]
Hi,

I'm following install guide provided on your web page, and I'm installing from ppa repo latest available version `1.0.2` of kolide.

When I'm running the prepare db, I get 

```
2017/03/23 10:13:45 FAIL 20161118212641_CreateTablePasswordResetRequests.go (Error 1067: Invalid default value for 'expires_at'), quitting migration.
```

I see that the same error was already reported on docker install in https://github.com/kolide/kolide-quickstart/issues/25, however I'm not running on docker but on clean ubuntu bare metal install.

**Comment by zwass** [comment]
Hi, sorry we missed this... What version of MySQL are you running this against? We've seen issues with users running MySQL older than 5.6.

**Comment by stachdude** [comment]
'mysqld  Ver 5.7.17-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))'

**Comment by zwass** [comment]
@stachdude I have a feeling that this is an issue with your MySQL timezone not being set to UTC. If you'd like help debugging it, please PM me at @zwass on the osquery slack (invite link: https://osquery-slack.herokuapp.com/).
