### ISSUE TITLE
Errors starting on Ubuntu 16

### ISSUE THREAD

**Issue by init99** [kolide/kolide-quickstart#38]
I'm getting this output when I attempt to start on Ubuntu 16

Starting kolidequickstart_redis_1
Starting kolidequickstart_mailhog_1
Starting kolidequickstart_mysql_1
Starting kolidequickstart_fleet_1
Waiting for MySQL to accept connections......
Waiting for Fleet server to accept connections.....................................................Error: Kolide failed to start up. Exiting.

Any advice on troubleshooting?

Thanks

**Comment by HLD** [comment]
I see what appears to be same issue on CentOS Linux release 7.4.1708 (Core)

Waiting for MySQL to accept connections......................
Waiting for Fleet server to accept connections.....................................................Error: Ke failed to start up. Exiting.

**Comment by HLD** [comment]
Looks like issue #25 with permissions for MySQL  - After removing containers and running as regular user, I was able to run the install script successfully.

**Comment by init99** [comment]
@HLD Were you able to start Fleet on Centos? If so do you have a PR?

**Comment by marpaia** [comment]
@init99 it seems like @HLD's problem was solved by not running the quickstart as root. Can you provide more information about what permissions you've been running the different parts of this process as?

**Comment by init99** [comment]
Starting with a clean VM it worked (why is noted below). However, I think some checks need to be added to demo.sh for permissions:

    1  sudo apt-get update && sudo apt-get upgrade
    2  sudo apt-get install     apt-transport-https     ca-certificates     curl     software-properties-common
    3  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    4  sudo apt-key fingerprint 0EBFCD88
    5  sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    6  $(lsb_release -cs) \
    7  stable"
    8  sudo apt-get update
    9  sudo apt-get install docker-ce
   10  sudo apt-get install git docker-compose
   11  git clone https://github.com/kolide/kolide-quickstart.git
   12  sudo groupadd docker
   13  sudo usermod -aG docker $USER

* At this point I logged off. In a previous run, I did not and I think the attempt to run docker and demo.sh without the right permissions permanently broke something... 

   14  cd kolide-quickstart/
   15  ./demo.sh up simple

Waiting for MySQL to accept connections........................
Waiting for Fleet server to accept connections...........
Finalizing Kolide setup...
######################################################################
# Setup complete. Please log in with username 'admin', password 'admin123#'
# Kolide server should now be accessible at https://127.0.0.1:8412 or https://kolide:8412.
# Note that a self-signed SSL certificate will generate a warning in the browser.
# To allow other hosts to enroll, you may want to create a DNS entry mapping kolide to the IP of this host.
######################################################################

This is on Ubuntu 16.04.
